### ISSUE TITLE
v3.0.1 compilation errors with Visual Studio 2015

### ISSUE THREAD

**Issue by pauljurczak** [Shark-ML/Shark#35] opened 2016-01-09 10:48 UTC
I'm trying to build v3.0.1 on Windows 7 64-bit with Visual Studio 2015 Update 1, x64 release configuration and I'm getting this error:

C:\Shark\src\Models\RNNet.cpp(42): error C2668: 'shark::size': ambiguous call to overloaded function

**Comment by Ulfgard** [comment] 2016-01-09 11:17
duplicate of #17

**Closed** 2016-02-28 08:37 UTC
