### ISSUE TITLE
'make_iterator_range': identifier not found error when following Nearest Neighbour tutorial

### ISSUE THREAD

**Issue by wcolejordan** [Shark-ML/Shark#212] opened 2018-01-05 18:53 UTC
I am trying to get KNN working but I am getting the error mentioned above.
The code I have is pretty much copied from the tutorial found at http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/tutorials/algorithms/nearestNeighbor.html although I have changed variable names.
```
void knn(ClassificationDataset const& trainingset, ClassificationDataset const& testset)
{
	KDTree<RealVector> tree(trainingset.inputs());
	TreeNearestNeighbors<RealVector, unsigned int> algorithm(trainingset, &tree);
	const unsigned int K = 1;
	NearestNeighborClassifier<RealVector> KNN(&algorithm, K);

	ZeroOneLoss<unsigned int> loss01;
	Data<unsigned int> predictions = KNN(testset.inputs());
	
	cout << K << "KNN Accuracy: " << (1. - loss01.eval(testset.labels(), predictions)) * 100 << "%" << endl;
}
```
I commented all lines out to go through one by one to see which it was failing at, the error is thrown at the first.
`KDTree<RealVector> tree(trainingset.inputs());` 

Full list of errors/warnings:
![image](https://user-images.githubusercontent.com/25622058/34623492-81783efc-f249-11e7-8c18-0c58422d6193.png)

Any assistance would be really appreciated!

**Comment by wcolejordan** [comment] 2018-01-06 16:33
In addition, when following the http://image.diku.dk/shark/sphinx_pages/build/html/rest_sources/tutorials/algorithms/svm.html tutorial with the following code:
```
double gamma = 0.5;
	GaussianRbfKernel<> kernel(gamma);
	KernelClassifier<RealVector> kc;
	double C = 1000.0;
	bool bias = true;
	CSvmTrainer<RealVector> trainer(&kernel, C, bias);

	ZeroOneLoss<unsigned int> loss;
	Data<unsigned int> output = kc(trainingset.inputs());
	double train_error = loss.eval(trainingset.labels(), output);
	cout << "Training error:\t" << train_error << endl;
	output = kc(testset.inputs());
	double test_error = loss.eval(testset.labels(), output);
	cout << "Test error:\t" << test_error << endl;
```
On build I am given the following errors:
![image](https://user-images.githubusercontent.com/25622058/34641654-2aa1ddfc-f2ff-11e7-99db-51dce5f1e866.png)

**Comment by Ulfgard** [comment] 2018-01-08 09:52
Hi!

The first error looks like an ADL-bug in the compiler. I think i have seen that one before already, might be fixed on master.

The second could be a missing include on our side (`#include <algorithm>` at the top of AnalyticProblems.h should fix it.)

The errors further down i can not reproduce from current master branch as line 424 is commented out. Which version of Shark are you using? Could you try with downloading the current master? The only downside of master is that there where some larger changes recently and i think the online docs are not updated yet. But the changes are mosty relevant for the neural networks part.

**Closed** 2018-03-07 22:13 UTC
