### ISSUE TITLE
Random forest trainer

### ISSUE THREAD

**Issue by arthur-leguennec** [Shark-ML/Shark#167] opened 2017-03-31 08:55 UTC
Hi,
I train my random forest by this way : 

    void train(double ratio, const std::vector<std::vector<float>>& samples, const std::vector<unsigned int>& labels)
	{
		std::vector<RealVector> inputs(samples.size());

		for (std::size_t i = 0; i < samples.size(); i++) {
			inputs.at(i).resize(samples.at(i).size());
			for (std::size_t j = 0; j < samples.at(0).size(); j++) {
				inputs.at(i)(j) = static_cast<double>(samples.at(i).at(j));
			}
		}

		ClassificationDataset data = createLabeledDataFromRange(inputs, labels);
		data.shuffle();
		data.makeIndependent();
		RFTrainer trainer(true, true);
		trainer.setOOBratio(ratio);
		RFClassifier model;
		trainer.train(model, data);
		m_featureImportance = model.featureImportances();
		m_OOBerror = model.OOBerror();
		m_model = model;
	}

But when I try to classify and get the label on my data test with : 

    RealVector input(mscdata.params.size()); // with mscdata.params a vector of float, that contains my data
    for (std::size_t i = 0; i < paramCount; i++) {
        input(i) = static_cast<double>(mscdata.params.at(i));
    }
    unsigned prediction = arg_max(m_model(input));

I have only one predicted class (the 1), like if my model is blocked on one class.

During the debub, I also remarked the label dimension of my model (after the training) have a non sense value, corredted by this code (before the training):

    std::size_t tmp = numberOfClasses(data);
    model.setLabelDimension(numberOfClasses(data));

Also, the weights of my model are all at 1.

**Comment by Ulfgard** [comment] 2017-03-31 09:11
Hi,

I need some more information.

Are the labels of the format 0,1,2,...,N-1 (where N is the number of classes)? What is the nonsense-value?
Is one class much more likely than the other classes? You can test this by printing the results of
```
std::vector<std::size_t> vec = classSizes(data);
for(std::size_t s : vec)
    std::cout<<s<<std::endl;
```

**Comment by arthur-leguennec** [comment] 2017-03-31 11:37
> Are the labels of the format 0,1,2,...,N-1 (where N is the number of classes)?

Yes, for now, I have 0 and 1, but I will have more classes later

> What is the nonsense-value?

14757395258967641292, the maximum value of `unsigned __int64`

> Is one class much more likely than the other classes?

Normally no, I have no problem to classify this data with a LDA with the same features. In my case, the random forest predicted all at 0 or 1.

> You can test this by printing the results of

    std::vector<std::size_t> vec = classSizes(data);
    for(std::size_t s : vec)
        std::cout<<s<<std::endl;

Not directly, but by debugging and with breakpoints, I find : 

    1000
    1000

**Comment by Ulfgard** [comment] 2017-04-03 12:05
Hi,

okay i had a bit of time to look into it. the labelDimension is not problematic, because it is not used (still should be fixed).

could you print the performance on the training set? you can do this in your train method(you can btw add m_model directly as argument to the trainer)

#include <shark/ObjectiveFunctions/Loss/ZeroOneLoss.h>

```
ZeroOneLoss<unsigned int, RealVector> loss;
cout << "Random Forest error: " << loss.eval(data.labels(),  model(data.inputs())) << endl;
```

**Comment by arthur-leguennec** [comment] 2017-04-03 14:44
Hi,

yes, I can do this. I have 0.000 so it's ok, the problem is when I tried to measure the accuracy for each class. `unsigned prediction = arg_max(m_model(input));` send me always 1 with `input` a data (not a dataset).

**Comment by Ulfgard** [comment] 2017-04-03 14:48
so the tree is probably okay but something later dies. good to know, i will check tomorrow.

I will check tomorrow.
________________________________

**Comment by arthur-leguennec** [comment] 2017-04-06 08:55
Hi, 

do you resolve the problem ?

Arthur

**Comment by Ulfgard** [comment] 2017-04-06 11:52
I have got trouble reproducing this. I used your code as a basis for a (hopefully) minimal example.
```

#include <shark/Data/DataDistribution.h> //includes small toy distributions
#include <shark/Algorithms/Trainers/RFTrainer.h> //the random forest trainer

#include <iostream> 

using namespace std; 
using namespace shark;

int main( int argc, char ** argv ) 
{
	double ratio = 0.7;
	Chessboard problem; // artificial benchmark data
	ClassificationDataset data = problem.generateDataset(1000);
	ClassificationDataset dataTest = problem.generateDataset(1000);

	data.shuffle();
	data.makeIndependent();
	RFTrainer trainer(true, true);
	trainer.setOOBratio(ratio);
	RFClassifier model;
	trainer.train(model, data);
	RealVector featureImportance = model.featureImportances();
	double OOBerror = model.OOBerror();
	RFClassifier m_model;
	m_model = model;

	
	for(auto elem: dataTest.elements()){
		unsigned prediction = arg_max(m_model(elem.input));
		std::cout<<prediction<<" "<<elem.label<<std::endl;
	}
	std::cout<<featureImportance<<std::endl;
	std::cout<<OOBerror<<std::endl;
}
```

Does the above work for you? It produces correct results on my machine. you can try replacing the datasets and evaluation by your routine but if this works, the error might be somewhere else.

**Comment by Ulfgard** [comment] 2017-11-10 14:26
We replaced the RF implementation. So this should be working.

**Closed by Ulfgard** 2017-11-10 14:26 UTC
