### ISSUE TITLE
Getting tree node information from Random Forests

### ISSUE THREAD

**Issue by inglada** [Shark-ML/Shark#211] opened 2017-12-29 11:01 UTC
Hi,
I would like to access to several levels of detailed information from the leaf nodes of a RF classifier. 
Right after training, I would need to get the training samples which end up in each node of each tree. At classification time, for every test sample, I would like to retrieve a unique identifier for the leaf node where the sample falls in every tree. 
This information would be very useful in order to estimate posterior probabilities for every sample.
Could you point me in the right direction to do that? I assume that the CARTree class should be slightly modified to that, since for instance, the leaf nodes don't store a unique ID, but an index to the label array.
Thank you.

**Comment by Ulfgard** [comment] 2017-12-29 12:06
Hi,

Solving the second question first is easier. I think for this you have at least to modify the CARTree class in models/trees so that evalPattern returns nodeId instead of the label. Then, you can just rewrite eval to return the label of the node with that id (last line in evalPattern). Of course you should make evalPattern public (and maybe give it a more telling name, e.g. "findLeaf".

Using these ids you can next try to solve the other task, simply by pushing the bootstrap sample through the tree in RFTrainer and record the leaf nodes. For the information about the inner nodes, you can for every sample just traverse the path upwards after findLeaf returns and add the sample to some array of "samples of node".

For this, you need the id of the parent of a node, which we do not store. You can generate the parent information using the node routines in the RFTree class. Start at node 0 and then proceed to left and right nodes storing their parent in an array
parents[nodeId] =parentId.

I would not add additional fields to the node objects because this slows down tree traversal(cache effects). Rather add separate arrays.

Does his help? Are you implementing some well known algorithm or do you try to roll your own?

Best,
Oswin




________________________________

**Comment by inglada** [comment] 2017-12-31 20:43
Hi,
Thanks for your reply. I was not thinking about the inner nodes, but just the leaves.

If I understand what you suggest, it would be impossible to use batches and getting the nodeId would require working with individual samples. Although this is not a major problem for my first question (identifying which training samples go into each leaf), this can be very slow when doing classification of large data sets.

I thought that maybe we could add a parameter (a bool member) to the CARTree class which would tell it to return either the label or the nodeId. What do you think about that?

What I want to do is using RF as a means to build a representation of a data set. This representation would be a vector of nodeIds (one per tree in the forest). Therefore, I was thinking about making the RF return the nodeIds instead of the labels. In this case, I don't know if it makes sense to modify the RFClassifier, or rather add the trees to something like the MeanModel but which would only build the vector of nodeIds.

Thanks.

**Comment by Ulfgard** [comment] 2018-01-03 10:46
Hi,

I am travelling so this reply is a bit shorter.

Trees can not take advantage of batch processing. What is done right now is that a batch is processed element by element.
What might slow you down is when a proxy to a matrix row is converted to a vector. We can prevent that by using template arguments. In that case there should be 0 cost.

You can not return label or node Id using a boolean flag because the label might have a different type. However you could try to convert this tree into a tree with integer labels for the rootid. This is a tad of work but might be done without changing any code, this just requires you to build your own trees.

However the mean model will likely break and you might want to use a different model which returns a sparse vector.

________________________________________

**Comment by inglada** [comment] 2018-01-16 15:09
Hi,

Thanks for your reply. 

> Trees can not take advantage of batch processing. What is done right now is that a batch is processed element by element. What might slow you down is when a proxy to a matrix row is converted to a vector. We can prevent that by using template arguments. In that case there should be 0 cost.

I don't understand what you mean by "using template arguments". Where do they would be used?

> You can not return label or node Id using a boolean flag because the label might have a different type. However you could try to convert this tree into a tree with integer labels for the rootid. This is a tad of work but might be done without changing any code, this just requires you to build your own trees.

Do you mean training the RF as usual and then copying the trained trees to new trees (with LabelType=unsigned int) where I would change the m_labels vector to contain the nodeId? I could iterate through the nodes, check thath they are leaves (node.leftId==0) and then do m_labels[node.rightIdOrIndex]=nodeId.

This would require a public access to a reference to m_labels or adding a public method to the class to do the work. 

What do you think?

> However the mean model will likely break and you might want to use a different model which returns a sparse vector.

Why a **sparse** vector? The vector should contain the nodeId for the leaf node activated for each tree. Wouldn't a std::vector be appropriate?

If I have to implement a model like this, which one would you suggest using as starting example?

Thanks again for your help.

**Comment by Ulfgard** [comment] 2018-01-19 13:45
Hi, sorry for the late reply.
The template arguments should be used at the findLeaf(Vector const& pattern) function as you correctly do it, this way you prevent that a matrix-row is converted to some RealVector or similar(which would be expensive). So you do exactly the right thing.

For the second: yes, you could do that and you do it correctly in your pull-request, but this will of course fail for regression. So what you should do is create a new tree using the node-creation routines already available.

The routines are:

createRoot() (creates an "empty" new root with nodeId=0)

transformInternalNode(std::size_t nodeId, std::size_t attributeIndex, double attributeValue)
transforms an "empty" node (for example the root node) into an internal node and creates the left/right "empty" children.

transformLeafNode(std::size_t nodeId, LabelType const& label)
turns an "empty" node into a leaf with a specified label (in your case the nodeId in the other tree).

so you could just traverse the initial tree and duplicate the structure. The reason i propose this is because you could at first keep this as your function in your code and don't have to push it (and thus do not face the problem that someone might remove this as an "unused" function).

**Comment by Ulfgard** [comment] 2018-01-24 10:13
is this fixed now? feel free to close if you managed to do all you wanted to do!

**Closed** 2018-01-24 11:42 UTC
